import Link from 'next/link';
import {AudioLines,MessageCircle,ArrowRight,Check,Mic,FileText,Sparkles,ChevronDown} from 'lucide-react';
import {OctiMascot} from '../../components/octi-mascot';
import './landing.css';
import {LiveSummaryDemo,ConversationDemo} from '../../components/landing-demos';
export default function LandingPage(){return <div className="octi-site">
<nav className="site-nav" aria-label="메인 메뉴"><Link className="site-wordmark" href="/landing">Octi<span>작은 이해, 큰 발견.</span></Link><div><a href="#experience">옥티 소개</a><a href="#flow">사용 방법</a><Link className="site-button mini" href="/">시작하기</Link></div></nav>
<section className="playful-hero"><div className="hero-art"><div className="hero-orbit"/><span className="floating-note note-one"><AudioLines size={24}/>듣고</span><span className="floating-note note-two"><MessageCircle size={24}/>묻고</span><span className="floating-note note-three"><Check size={23}/>이해하고!</span><span className="art-spark spark-one">✦</span><span className="art-spark spark-two">✦</span><OctiMascot/><div className="mascot-floor"/></div><div className="playful-hero-copy"><span className="site-eyebrow"><span/>나의 AI 학습 친구, 옥티</span><h1>어려운 강의도,<br/><em>옥티랑 한 걸음씩.</em></h1><p>듣는 동안, 실시간으로 요약이 쌓여요.<br/>궁금한 순간엔 옥티와 바로 대화하세요.</p><div className="site-hero-actions"><Link href="/" className="site-button">옥티와 시작하기<ArrowRight size={20}/></Link><a href="#experience" className="site-button secondary">어떻게 사용하는지 보기<ChevronDown size={18}/></a></div><small>설치 없이 브라우저에서 시작해요.</small></div></section>
<div className="site-benefit-strip"><span><Mic size={21}/>실시간 강의 요약</span><span><FileText size={21}/>자료와 함께</span><span><MessageCircle size={21}/>맥락을 아는 대화</span><span><Sparkles size={21}/>눈으로 보는 설명</span></div>
<section id="experience" className="site-feature"><div className="feature-copy"><span className="site-kicker">01 · 실시간으로 정리해요</span><h2>요약은 실시간으로.<br/>이해는 듣는 순간부터.</h2><p>강의를 듣는 동안 핵심 요약이 바로 쌓여요.<br/>헷갈린 부분은 원문과 함께 다시 살펴보고,<br/>강의 흐름을 놓치지 않고 이해해요.</p><a href="/" className="site-text-link">첫 강의 기록하기<ArrowRight size={17}/></a></div><div className="illustration-panel lavender"><LiveSummaryDemo/><span className="sticker recording-sticker"><Mic size={20}/>놓치지 않을게!</span></div></section>
<section className="site-feature reverse"><div className="feature-copy"><span className="site-kicker blue">02 · 궁금하면 물어봐요</span><h2>“잠깐, 왜 그렇지?”<br/>그 순간부터 함께.</h2><p>처음부터 다시 설명할 필요 없어요.<br/>강의의 맥락과 선택한 자료를 바탕으로<br/>옥티와 궁금한 부분을 살펴보세요.</p><a href="/" className="site-text-link blue">옥티에게 질문하기<ArrowRight size={17}/></a></div><div className="illustration-panel sky"><ConversationDemo/><span className="sticker question-sticker">아하! 이제 알겠어 ✦</span></div></section>
<section className="site-feature"><div className="feature-copy"><span className="site-kicker coral">03 · 눈으로도 이해해요</span><h2>말로는 어려웠던 게,<br/>한눈에 보일 때.</h2><p>답변을 비교표, 흐름도, 수식으로 살펴보세요.<br/>텍스트에서 한 걸음 더 나아가,<br/>설명의 연결을 눈으로 확인해요.</p><a href="/" className="site-text-link coral">강의 이해 이어가기<ArrowRight size={17}/></a></div><div className="illustration-panel peach"><div className="visual-card"><span className="demo-label">시각 설명 예시</span><h3>평균에서 순간으로.</h3><svg viewBox="0 0 340 190" role="img" aria-label="두 점이 가까워지며 접선으로 이어지는 곡선 예시"><path d="M35 20V160H310" fill="none" stroke="#ddd" strokeWidth="2"/><path d="M50 147Q180 147 290 30" fill="none" stroke="#9253f4" strokeWidth="5" strokeLinecap="round"/><path d="M90 165L290 40" fill="none" stroke="#f3ae3d" strokeWidth="3" strokeDasharray="7 7"/><circle cx="145" cy="122" r="7" fill="#9253f4"/><circle cx="250" cy="68" r="7" fill="#9253f4"/><text x="130" y="148">a</text><text x="246" y="96">a+h</text></svg><div className="visual-equation"><span>두 점의 기울기</span><ArrowRight size={18}/><b>한 점의 기울기</b></div></div><span className="sticker visual-sticker"><Sparkles size={19}/>이해가 연결되는 순간</span></div></section>
<section id="flow" className="site-flow"><span className="site-kicker">실시간 요약부터, 맥락을 잇는 대화까지</span><h2>듣는 순간부터, 이해까지 함께.</h2><div className="flow-cards">{[{icon:<AudioLines size={27}/>,title:'듣는 동안 요약이 쌓여요',text:'강의가 이어지는 동안, 핵심 내용을 실시간으로 정리해요.'},{icon:<MessageCircle size={27}/>,title:'궁금한 순간, 바로 대화해요',text:'녹음은 계속하면서, 옥티와 질문과 답변을 주고받아요.'},{icon:<Sparkles size={29}/>,title:'강의 맥락에서 이해해요',text:'방금 들은 설명과 선택한 자료를 바탕으로 함께 살펴봐요.'}].map((step,index)=><article key={step.title}><span className={'flow-icon color-'+index}>{step.icon}</span><small>STEP 0{index+1}</small><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></section>
<section className="site-final"><div className="final-mascot"><OctiMascot/></div><span className="site-kicker">옥티가 기다리고 있어요</span><h2>다음 강의는,<br/>조금 더 즐겁게.</h2><Link className="site-button" href="/">옥티와 시작하기<ArrowRight size={20}/></Link></section>
<footer className="playful-footer"><div><Link className="site-wordmark" href="/landing">Octi</Link><p>듣고, 묻고, 이해하는 순간까지.<br/>나의 속도로 배우는 AI 학습 공간.</p></div><nav aria-label="푸터 메뉴"><b>옥티와 함께</b><a href="#experience">서비스 소개</a><a href="#flow">사용 방법</a><Link href="/">시작하기</Link></nav><div className="site-copyright">© 2026 OCTI. ALL RIGHTS RESERVED.<span>작은 이해, 큰 발견.</span></div></footer>
</div>}
